const {createClient}=supabase;const client=createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);const bucket=window.SUPABASE_BUCKET;const defs=[['company','公司形象','Company','▦'],['factory','厂房环境','Factory','▤'],['workshop','生产车间','Workshop','⚙'],['vffs','VFFS设备','VFFS Machine','▥'],['food','食品包装','Food Packaging','◈'],['weighing','自动称重','Weighing System','⌗'],['cases','项目案例','Case Studies','▣'],['videos','视频中心','Video','▶']];let items=[];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function ensureSlots(){const {data,error}=await client.from('gallery_items').select('*').order('sort_order',{ascending:true});if(error)throw error;const existing=new Set((data||[]).map(x=>x.slot_key));const missing=defs.filter(d=>!existing.has(d[0])).map((d,i)=>({slot_key:d[0],title:d[1],description:'',image_url:'',video_url:'',sort_order:(data?.length||0)+i+1,published:true}));if(missing.length){const r=await client.from('gallery_items').insert(missing);if(r.error)throw r.error}const r=await client.from('gallery_items').select('*').order('sort_order',{ascending:true});if(r.error)throw r.error;items=r.data||[]}
function render(){const grid=$('adminGrid');grid.innerHTML=items.map((x,i)=>{const media=x.image_url?`<img src="${esc(x.image_url)}" alt="">`:x.video_url?`<video src="${esc(x.video_url)}" controls></video>`:`<span>${esc(defs.find(d=>d[0]===x.slot_key)?.[1]||'待上传')}</span>`;return `<article class="admin-card"><div class="thumb">${media}</div><div class="small">内容位 ${i+1} · ${esc(x.slot_key)}</div><div class="row"><div class="field"><label>标题</label><input id="title-${x.id}" value="${esc(x.title)}"></div><div class="field"><label>排序</label><input id="sort-${x.id}" type="number" value="${x.sort_order}"></div></div><div class="field"><label>说明</label><textarea id="desc-${x.id}">${esc(x.description||'')}</textarea></div><label class="check"><input id="pub-${x.id}" type="checkbox" ${x.published?'checked':''}> 发布到公开图库</label><div class="row" style="margin-top:12px"><label class="secondary">上传图片 <input hidden type="file" accept="image/*" onchange="uploadMedia(${x.id},this,'image')"></label><label class="secondary">上传视频 <input hidden type="file" accept="video/*" onchange="uploadMedia(${x.id},this,'video')"></label><button class="primary" onclick="saveItem(${x.id})">保存</button><button class="danger" onclick="deleteMedia(${x.id})">删除当前媒体</button></div><div class="move" style="margin-top:9px"><button class="secondary" onclick="moveItem(${x.id},-1)">↑ 上移</button><button class="secondary" onclick="moveItem(${x.id},1)">↓ 下移</button></div><div class="status" id="status-${x.id}"></div></article>`}).join('')}
async function saveItem(id){const x=items.find(a=>a.id===id);if(!x)return;const payload={title:$(`title-${id}`).value,description:$(`desc-${id}`).value,sort_order:Number($(`sort-${id}`).value)||x.sort_order,published:$(`pub-${id}`).checked};const {error}=await client.from('gallery_items').update(payload).eq('id',id);if(error)return toast('保存失败：'+error.message);toast('已保存');await ensureSlots();render()}
window.saveItem=saveItem;
function ext(file){const p=file.name.split('.');return p.length>1?p.pop().toLowerCase():'bin'}
async function uploadMedia(id,input,type){const file=input.files?.[0];if(!file)return;const status=$(`status-${id}`);status.textContent='正在上传…';const x=items.find(a=>a.id===id);const path=`gallery/${x.slot_key}/${type}-${Date.now()}.${ext(file)}`;const {error}=await client.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type||undefined});if(error){status.textContent='上传失败：'+error.message;return}const {data}=client.storage.from(bucket).getPublicUrl(path);const payload=type==='image'?{image_url:data.publicUrl}:{video_url:data.publicUrl};const {error:e}=await client.from('gallery_items').update(payload).eq('id',id);if(e){status.textContent='数据库更新失败：'+e.message;return}status.textContent='上传成功';toast('媒体已上传');await ensureSlots();render()}
window.uploadMedia=uploadMedia;
function pathFromUrl(url){const marker=`/storage/v1/object/public/${bucket}/`;const i=(url||'').indexOf(marker);return i>=0?url.slice(i+marker.length):null}
async function deleteMedia(id){const x=items.find(a=>a.id===id);if(!x)return;if(!confirm(`确定删除“${x.title}”当前图片/视频吗？`))return;const paths=[pathFromUrl(x.image_url),pathFromUrl(x.video_url)].filter(Boolean);if(paths.length)await client.storage.from(bucket).remove(paths);const {error}=await client.from('gallery_items').update({image_url:'',video_url:''}).eq('id',id);if(error)return toast('删除失败：'+error.message);toast('当前媒体已删除');await ensureSlots();render()}
window.deleteMedia=deleteMedia;
async function moveItem(id,delta){const i=items.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=items.length)return;const a=items[i],b=items[j];const r1=await client.from('gallery_items').update({sort_order:b.sort_order}).eq('id',a.id);const r2=await client.from('gallery_items').update({sort_order:a.sort_order}).eq('id',b.id);if(r1.error||r2.error)return toast('排序失败');await ensureSlots();render()}
window.moveItem=moveItem;
async function start(){const {data:{session}}=await client.auth.getSession();if(session)showDashboard(session);client.auth.onAuthStateChange((_e,s)=>{if(s)showDashboard(s);else showLogin()})}
async function showDashboard(session){$('loginBox').style.display='none';$('dashboard').style.display='block';$('topActions').style.display='flex';$('userLabel').textContent=session.user.email;try{await ensureSlots();render()}catch(e){$('adminGrid').innerHTML=`<div class="notice">读取后台失败：${esc(e.message)}<br>请检查 gallery_items 的 Data API 暴露和 RLS 权限。</div>`}}
function showLogin(){$('loginBox').style.display='block';$('dashboard').style.display='none';$('topActions').style.display='none'}
$('loginBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;const s=$('loginStatus');s.textContent='登录中…';const {error}=await client.auth.signInWithPassword({email,password});if(error)s.textContent='登录失败：'+error.message;else s.textContent=''};$('logoutBtn').onclick=()=>client.auth.signOut();start();
